### ISSUE TITLE
I can't toggle Menu bar back on

### ISSUE THREAD

**Issue by vinisalazar** [klauscfhq/tusk#107]
Hi, I toggled the menu bar off and now I can't find where to turn it back on. Sorry for opening the issue but I couldn't solve it.

Thanks
V

**Comment by vinisalazar** [comment]
It's Alt. I wasn't at my brightest when I opened this issue

**Comment by brandones** [comment]
You were perfectly bright; this is a design problem and should be addressed.

**Comment by rodrigorras** [comment]
oh no, I also deleted mine... lol

**Comment by jimknock** [comment]
I have a terrible memory but I am fairly good at figuring things out. 

I've been bitten by this at least three times in the past year. 

To me, the issue is that there are no visual clues regarding Alt once the menu has been toggled off.
Viewed another way, there is a dropdown to turn it off. But there is no dropdown to turn it on.
