### ISSUE TITLE
Issue: Single mouse-click in `Notes Panel` moves entire app Window

### ISSUE THREAD

**Issue by cswarth** [klauscfhq/tusk#37]
## Description

Single mouse click and drag within note panel moves window instead of selecting text.
Multi-click and drag seems to work ok.

This may be a Mac-only bug?

## Environment

OS Type: 	Darwin
OS Platform:	darwin
OS Release: 	16.7.0
Architecture: 	x64

Tusk: 0.9.1

**Comment by klauscfhq** [comment]
It is actually a quite easy `Electron` related fix. Pull Request super welcome if anyone wants this : )

**Comment by nataliastanko** [comment]
I actually still have this issue running the Tusk-0.23.0.dmg

**Comment by nataliastanko** [comment]
**Walkaround for impatient mac tusk users**

[#206](https://github.com/klaussinani/tusk/issues/206) [#43](https://github.com/klaussinani/tusk/issues/43)

A temporary walkaround that fixed* the problem (improved the usability enormously). 

* Downsides I have found so far is that you won't be able to move the application window (so the so-called fix will break this functionality), thought resizing is still possible. The app will hook itself at the display's left top corner.
The other downside is of course not using the official tusk release (but we have not seen it in a while).

1. Follow the instructions from the [development](https://github.com/klaussinani/tusk#development) section
2. Change the value from drag to no-drag on the body element in browser.css

```
body {
    -webkit-app-region: no-drag;
}
```

3. Run the app

On this day I am not familiar with electron and don't know the exact element to assign the no-drag value, that's why I have changed it for the body. But I am a happy tusk user from now on.
